services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rwd\ContaoCustomArticlesBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources}'

    Rwd\ContaoCustomArticlesBundle\Library\HexToRgba:
        public: true
