services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rwd\ContaoCustomArticlesBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources}'

    rwd.contao_custom_articles_bundle.hex_to_rgba:
        alias: Rwd\ContaoCustomArticlesBundle\Library\HexToRgba
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'
        public: true