services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rwd\ContaoCustomArticlesBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources}'

    rwd.contao_custom_articles_bundle.hex_to_rgba:
        class: Rwd\ContaoCustomArticlesBundle\Library\HexToRgba
        public: true
